# Generated by Django 4.2.2 on 2023-08-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='created_at',
        ),
    ]
