# Generated by Django 4.2.2 on 2023-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.TextField(max_length=100),
        ),
    ]
