# Generated by Django 4.2.2 on 2023-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
