# Generated by Django 4.2.2 on 2023-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(max_length=30),
        ),
    ]
