# Generated by Django 4.2.2 on 2023-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_education_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=100)),
                ('project_description', models.TextField(max_length=1000)),
                ('project_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
