# Generated by Django 4.2.2 on 2023-08-04 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0007_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
