# Generated by Django 4.2.2 on 2023-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_personaldata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
