# Generated by Django 4.2.2 on 2023-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_personaldata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='specialization',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='sphere',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
