# Generated by Django 4.2.2 on 2023-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_personaldata_specialization_personaldata_sphere'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='slogan',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldata',
            name='smth_to_say',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
