# Generated by Django 4.2.2 on 2023-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_personaldata_slogan_personaldata_smth_to_say'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
