# Generated by Django 4.2.2 on 2023-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_delete_image_alter_projects_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
