# Generated by Django 4.2.2 on 2023-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_message_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
