# Generated by Django 4.2.2 on 2023-08-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_projects_project_link'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='message',
        #     name='email',
        # ),
        # migrations.RemoveField(
        #     model_name='message',
        #     name='message',
        # ),
        # migrations.RemoveField(
        #     model_name='message',
        #     name='phone_number',
        # ),
    ]
