# Generated by Django 4.2.2 on 2023-08-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_projects_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
