# Generated by Django 4.2.2 on 2023-08-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_remove_message_email_remove_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='asdasd@asdas.asd', max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='asdasdads'),
        ),
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.IntegerField(default='78945678'),
        ),
    ]
