# Generated by Django 4.2.2 on 2023-08-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_message_full_name'),
        ('resume', '0017_message_email_message_message_message_phone_number'),
    ]

    operations = [
    ]
